#!/bin/sh

#PJM -L "rscunit=ito-a"
#PJM -L "rscgrp=ito-s"
#PJM -L "vnode=4"
#PJM -L "vnode-core=36"
#PJM -L "elapse=24:00:00"
#PJM -j
#PJM -X
#PJM --no-stging

module load openfoam/v1812_ompi

cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh
runApplication surfaceFeatureExtract
runApplication decomposePar
runParallel snappyHexMesh -overwrite
restore0Dir -processor
runParallel $(getApplication)
runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime

exit

#------------------------------------------------------------------------------
